## Project Description: Next Word Prediction Using LSTM
#### Project Overview:

This project aims to develop a deep learning model for predicting the next word in a given sequence of words. The model is built using Long Short-Term Memory (LSTM) networks, which are well-suited for sequence prediction tasks. The project includes the following steps:

1- Data Collection: We use the text of Shakespeare's "Hamlet" as our dataset. This rich, complex text provides a good challenge for our model.

2- Data Preprocessing: The text data is tokenized, converted into sequences, and padded to ensure uniform input lengths. The sequences are then split into training and testing sets.

3- Model Building: An LSTM model is constructed with an embedding layer, two LSTM layers, and a dense output layer with a softmax activation function to predict the probability of the next word.

4- Model Training: The model is trained using the prepared sequences, with early stopping implemented to prevent overfitting. Early stopping monitors the validation loss and stops training when the loss stops improving.

5- Model Evaluation: The model is evaluated using a set of example sentences to test its ability to predict the next word accurately.

6- Deployment: A Streamlit web application is developed to allow users to input a sequence of words and get the predicted next word in real-time.

In [1]:
# Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd

# Load the dataset for Hamlet, Macbeth and Julius Caesar from the Gutenberg corpus
hamlet_data = gutenberg.raw('shakespeare-hamlet.txt')
macbeth_data = gutenberg.raw('shakespeare-macbeth.txt')
caesar_data = gutenberg.raw('shakespeare-caesar.txt')

# Save the Hamlet text to a file
with open('hamlet.txt', 'w') as file:
    file.write(hamlet_data)

# Save the Macbeth and Caesar texts to their respective files
with open('macbeth.txt', 'w') as file:
    file.write(macbeth_data)

with open('caesar.txt', 'w') as file:
    file.write(caesar_data)

# Combine the text content of all three works
final_text = hamlet_data + "\n" + macbeth_data + "\n" + caesar_data

# Save the combined text into 'final.txt'
with open('final.txt', 'w') as file:
    file.write(final_text)

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.


In [2]:
## Data Preprocessing

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

##laod the dataset
with open('final.txt','r') as file:
    text=file.read().lower()

## Tokenize the text-creating indexes for words
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
total_words

7804

In [3]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'i': 4,
 'of': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'that': 9,
 'in': 10,
 'it': 11,
 'is': 12,
 'not': 13,
 'his': 14,
 'with': 15,
 'this': 16,
 'me': 17,
 'your': 18,
 'for': 19,
 'but': 20,
 'he': 21,
 'be': 22,
 'haue': 23,
 'him': 24,
 'what': 25,
 'as': 26,
 'so': 27,
 'will': 28,
 'our': 29,
 'ham': 30,
 'all': 31,
 'thou': 32,
 'we': 33,
 'are': 34,
 'shall': 35,
 'no': 36,
 'lord': 37,
 'then': 38,
 'on': 39,
 'do': 40,
 'by': 41,
 'if': 42,
 'come': 43,
 'enter': 44,
 'king': 45,
 'they': 46,
 'good': 47,
 'now': 48,
 'thy': 49,
 'let': 50,
 'from': 51,
 'caesar': 52,
 'at': 53,
 'was': 54,
 'which': 55,
 'or': 56,
 'vs': 57,
 'them': 58,
 'did': 59,
 'thee': 60,
 'more': 61,
 'their': 62,
 'know': 63,
 'there': 64,
 'like': 65,
 'brutus': 66,
 'would': 67,
 'when': 68,
 'how': 69,
 'vpon': 70,
 'bru': 71,
 'well': 72,
 'her': 73,
 'hath': 74,
 'selfe': 75,
 'am': 76,
 'man': 77,
 'macb': 78,
 'yet': 79,
 'why': 80,
 'should': 81,
 'may': 82,
 '

In [4]:
## create input sequences
input_sequences=[]
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)



In [5]:
input_sequences

[[1, 837],
 [1, 837, 5],
 [1, 837, 5, 110],
 [1, 837, 5, 110, 41],
 [1, 837, 5, 110, 41, 1816],
 [1, 837, 5, 110, 41, 1816, 1817],
 [1, 837, 5, 110, 41, 1816, 1817, 2389],
 [616, 1818],
 [616, 1818, 1819],
 [616, 1818, 1819, 935],
 [44, 838],
 [44, 838, 2],
 [44, 838, 2, 2390],
 [44, 838, 2, 2390, 207],
 [44, 838, 2, 2390, 207, 3552],
 [838, 575],
 [838, 575, 64],
 [839, 258],
 [839, 258, 351],
 [839, 258, 351, 17],
 [839, 258, 351, 17, 150],
 [839, 258, 351, 17, 150, 1072],
 [18, 75],
 [936, 319],
 [936, 319, 202],
 [936, 319, 202, 1],
 [936, 319, 202, 1, 45],
 [839, 838],
 [936, 21],
 [839, 6],
 [839, 6, 43],
 [839, 6, 43, 84],
 [839, 6, 43, 84, 3553],
 [839, 6, 43, 84, 3553, 70],
 [839, 6, 43, 84, 3553, 70, 18],
 [839, 6, 43, 84, 3553, 70, 18, 379],
 [936, 89],
 [936, 89, 48],
 [936, 89, 48, 3554],
 [936, 89, 48, 3554, 1073],
 [936, 89, 48, 3554, 1073, 300],
 [936, 89, 48, 3554, 1073, 300, 60],
 [936, 89, 48, 3554, 1073, 300, 60, 3],
 [936, 89, 48, 3554, 1073, 300, 60, 3, 273],
 [93

In [6]:
# Pad Sequences
max_sequence_len=max([len(x) for x in input_sequences])
max_sequence_len

14

In [7]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    1,  837],
       [   0,    0,    0, ...,    1,  837,    5],
       [   0,    0,    0, ...,  837,    5,  110],
       ...,
       [   0,    0,    0, ...,    1,  837,    5],
       [   0,    0,    0, ...,  837,    5, 7803],
       [   0,    0,    0, ...,    5, 7803,   52]], dtype=int32)

In [8]:
##create predicitors and label
import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]

In [9]:
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  837],
       [   0,    0,    0, ...,    1,  837,    5],
       ...,
       [   0,    0,    0, ..., 2234,    1,  837],
       [   0,    0,    0, ...,    1,  837,    5],
       [   0,    0,    0, ...,  837,    5, 7803]], dtype=int32)

In [10]:
y

array([ 837,    5,  110, ...,    5, 7803,   52], dtype=int32)

In [11]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [12]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [13]:
# Define early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

In [14]:
## Train our LSTM RNN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,GRU

## Define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 13, 100)           780400    
                                                                 
 lstm (LSTM)                 (None, 13, 150)           150600    
                                                                 
 dropout (Dropout)           (None, 13, 150)           0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               100400    
                                                                 
 dense (Dense)               (None, 7804)              788204    
                                                                 
Total params: 1819604 (6.94 MB)
Trainable params: 1819604 (6.94 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
## GRU RNN
## Define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(GRU(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 13, 100)           780400    
                                                                 
 gru (GRU)                   (None, 13, 150)           113400    
                                                                 
 dropout_1 (Dropout)         (None, 13, 150)           0         
                                                                 
 gru_1 (GRU)                 (None, 100)               75600     
                                                                 
 dense_1 (Dense)             (None, 7804)              788204    
                                                                 
Total params: 1757604 (6.70 MB)
Trainable params: 1757604 (6.70 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
## Train the model
history=model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),verbose=1,callbacks=[early_stopping])


Epoch 1/50
1469/1469 [==============================] - 94s 62ms/step - loss: 7.0613 - accuracy: 0.0335 - val_loss: 6.8228 - val_accuracy: 0.0448
Epoch 2/50
1469/1469 [==============================] - 87s 59ms/step - loss: 6.4844 - accuracy: 0.0496 - val_loss: 6.6748 - val_accuracy: 0.0627
Epoch 3/50
1469/1469 [==============================] - 87s 59ms/step - loss: 6.1443 - accuracy: 0.0745 - val_loss: 6.6402 - val_accuracy: 0.0776
Epoch 4/50
1469/1469 [==============================] - 87s 59ms/step - loss: 5.8490 - accuracy: 0.0886 - val_loss: 6.6720 - val_accuracy: 0.0777
Epoch 5/50
1469/1469 [==============================] - 86s 58ms/step - loss: 5.5794 - accuracy: 0.0963 - val_loss: 6.7439 - val_accuracy: 0.0831
Epoch 6/50
1469/1469 [==============================] - 85s 58ms/step - loss: 5.3223 - accuracy: 0.1059 - val_loss: 6.8528 - val_accuracy: 0.0816


In [17]:
# Function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]  # Ensure the sequence length matches max_sequence_len-1
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [18]:
input_text="To be or not to be"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:To be or not to be
Next Word PRediction:a


In [19]:
## Save the model
model.save("next_word_lstm.h5")
## Save the tokenizer
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [20]:
input_text="  Barn. Last night of all,When yond same"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:  Barn. Last night of all,When yond same
Next Word PRediction:lord


In [21]:
def predict_next_word(model, tokenizer, input_text, max_sequence_len):
    # Convert input text to sequence of integers
    sequence = tokenizer.texts_to_sequences([input_text])
    sequence = pad_sequences(sequence, maxlen=max_sequence_len, padding='pre')

    # Predict the next word index
    predicted_probabilities = model.predict(sequence)
    predicted_index = np.argmax(predicted_probabilities, axis=-1)

    # Get the word corresponding to the predicted index
    predicted_word = tokenizer.index_word[predicted_index[0]]
    return predicted_word

# Define the input text and the number of predictions
input_text = "To be or not to be"
print(f"Input text: {input_text}")

# Set max sequence length based on the model's input shape
max_sequence_len = model.input_shape[1] + 1

# Perform the prediction 10 times
for _ in range(5):
    next_word = predict_next_word(model, tokenizer, input_text, max_sequence_len)
    input_text += ' ' + next_word  # Append the predicted word to the input text
    print(f"Next Word Prediction: {next_word}")

Input text: To be or not to be
1/1 [==============================] - 1s 572ms/step
Next Word Prediction: a
1/1 [==============================] - 0s 25ms/step
Next Word Prediction: king
1/1 [==============================] - 0s 25ms/step
Next Word Prediction: of
1/1 [==============================] - 0s 25ms/step
Next Word Prediction: the
1/1 [==============================] - 0s 25ms/step
Next Word Prediction: time
